# Generated by Django 4.2.1 on 2023-05-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("folder", models.CharField(max_length=255)),
            ],
        ),
    ]
