# Generated by Django 4.2.1 on 2023-06-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hack", "0002_remove_worker_user_alter_vidange_worker_associated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=255, unique=True)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
            ],
        ),
    ]
