# Generated by Django 4.2.1 on 2023-06-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Hack", "0003_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vidange",
            name="worker_associated",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Hack.worker"
            ),
        ),
    ]
